# Generated by Django 5.0.7 on 2024-07-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='景点名称')),
                ('desc', models.CharField(blank=True, max_length=128, null=True, verbose_name='景点描述')),
                ('content', models.TextField(verbose_name='景点内容')),
                ('img', models.ImageField(max_length=256, upload_to='%Y%m/sight', verbose_name='图片地址')),
                ('img_banner', models.ImageField(max_length=256, upload_to='%Y%m/sight', verbose_name='横幅图片地址')),
                ('score', models.FloatField(default=5, verbose_name='评分')),
                ('province', models.CharField(max_length=32, verbose_name='省份')),
                ('city', models.CharField(max_length=32, verbose_name='城市')),
                ('area', models.CharField(blank=True, max_length=32, null=True, verbose_name='区/县')),
                ('town', models.CharField(blank=True, max_length=32, null=True, verbose_name='乡镇')),
                ('min_price', models.FloatField(verbose_name='最低价格')),
                ('is_hot', models.SmallIntegerField(default=0, verbose_name='是否热门')),
                ('is_star', models.SmallIntegerField(default=0, verbose_name='是否精选')),
                ('is_valid', models.SmallIntegerField(default=1, verbose_name='是否有效')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'sight',
                'ordering': ['-update_at'],
            },
        ),
    ]
