# Generated by Django 5.0.7 on 2024-07-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论人数'),
        ),
    ]
